version: '3.9'

services:
    app:
        build: .
        restart: unless-stopped
        depends_on:
            - db
        environment:
            - NODE_ENV=production
            - MONGO_URL=mongodb://db:27017/envman
            - API_PORT=${API_PORT}
            - API_URL=${API_URL}
            - API_TOKEN=${API_TOKEN}
            - CORS_ORIGIN=${CORS_ORIGIN}
        volumes:
            - ./logs:/var/log
    db:
        image: mongo:latest
        # image: mongo:6.0.0
        restart: unless-stopped
        container_name: db
        command: ['--bind_ip_all', '--replSet', 'dbrs']
        ports:
            - 27018:27017
        depends_on:
            - db2
            - db3
        links:
            - db2
            - db3
        volumes:
            - onboarding-db-data:/data/db
            - onboarding-db-configdb:/data/configdb
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    db2:
        image: mongo:latest
        restart: unless-stopped
        container_name: db2
        command: ['--bind_ip_all', '--replSet', 'dbrs']
        ports:
            - 27019:27017
        volumes:
            - onboarding-db-data2:/data/db
            - onboarding-db-configdb2:/data/configdb
    db3:
        image: mongo:latest
        restart: unless-stopped
        container_name: db3
        command: ['--bind_ip_all', '--replSet', 'dbrs']
        ports:
            - 27020:27017
        volumes:
            - onboarding-db-data3:/data/db
            - onboarding-db-configdb3:/data/configdb
    nginx:
        image: nginx
        restart: unless-stopped
        container_name: nginx-proxy
        ports:
            - 4000:4000
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        depends_on:
            - app
volumes:
    envman-db-data:
    envman-db-configdb:
    envman-db-data2:
    envman-db-configdb2:
    envman-db-data3:
    envman-db-configdb3:
